postgres:
  image: postgres:12.3
  restart: always
  environment:
    POSTGRES_USER: 'mobydock'
    POSTGRES_PASSWORD: 'yourpassword'
    POSTGRES_HOST_AUTH_METHOD: 'trust'
  ports:
    - '5432:5432'
  volumes:
    - ~/.docker-volumes/mobydock/postgresql/data:/var/lib/postgresql/data

redis:
  image: redis:6.0.5
  ports:
    - '6379:6379'
  volumes:
    - ~/.docker-volumes/mobydock/redis/data:/var/lib/redis/data

mobydock:
  build: .
  links:
    - postgres
    - redis
  volumes:
    - .:/mobydock
  ports:
    - '8000:8000'
  env_file:
    - .mobydock.env